title: Sam Kneppel's Blog
email: samuelkneppel@gmail.com
description: >-
  A personal blog dedicated to sharing my experiences and learnings in the field of cybersecurity.
baseurl: ""
url: "samuelkneppel.github.io"
twitter_username: samuelkneppel
github_username:  samuelkneppel

theme: minima
plugins:
  - jekyll-feed