title: Sam Kneppel's Blog
email: samuelkneppel@gmail.com
description: >-
  An IT Systems Engineering and Cyber Security Blog
baseurl: ""
url: "samuelkneppel.github.io"
twitter_username: samuelkneppel
github_username:  samuelkneppel

theme: minima
plugins:
  - jekyll-feed